        <div id="temp_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="/index.php">Home</a></li>
                <li><a href="/cv.php">CV</a></li>
                <li><a href="/books.php">Books</a>
                    <ul>
                        <li><span class="top"></span><span class="bottom"></span></li>
                        <li><a href="/books.php#6">Arabic Civilizations ...</a></li>
                        <li><a href="/books.php#0">Strategic Information ...</a></li>
                        <li><a href="/books.php#1">Data Mining ...</a></li>
                        <li><a href="/books.php#2">Diversity in ...</a></li>
                        <li><a href="/books.php#3">Human Resources ...</a></li>
                        <li><a href="/books.php#4">The Menu ...</a></li>
			            <li><a href="/books.php#5">Human Resources In...</a></li>
                    </ul>
                </li>
                <li><a href="/art.php">Articles</a>
                    <ul>
                        <li><span class="top"></span><span class="bottom"></span></li>
                        <li><a href="/art.php#1">English Articles</a></li>
                        <li><a href="/art.php#2">Arabic Articles</a></li>
                  	</ul>
                </li>
				<li><a href="/tut.php">Tutoring</a></li>
                <li><a href="/gal.php">Galleries</a></li>
				<li><a href="/sites.php">Sites</a></li>
                <li><a href="/contact.php">Contact</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of temp_menu -->
    </div> <!-- END of header -->
